name: 'Level 4: Join the Simulation'
description: 'Join the queue to be assigned to either the Red or Blue Team.'
title: "Level 4 Sign-Up: <Your GitHub Handle>"
labels: ['level-4', 'pending-assignment']
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the final challenge! You are about to join the queue for the Red vs. Blue simulation.
        
        **To ensure the game is fair, teams will be balanced automatically.** You will be assigned to the team with fewer members at the time you create this issue.
  - type: checkboxes
    id: confirmation-checklist
    attributes:
      label: Confirmation Checklist
      description: Please confirm the following before joining the simulation.
      options:
        - label: I have read and understood the rules and winning conditions in the `level4/README.md`.
          required: true
        - label: I understand that my team will be assigned automatically to ensure balance.
          required: true
        - label: I understand that my team has a 48-hour time limit to make a move once our turn begins.
          required: true
