name: 'Level 4: Join the Simulation'
description: 'Join either the Red Team or the Blue Team for the Data Heist challenge.'
title: "Level 4 Sign-Up: <Your GitHub Handle>"
labels: ['level-4']
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the final challenge! Please read the main instructions in `level4/README.md` before joining a team. This is a competitive, team-based exercise.
  - type: dropdown
    id: team-choice
    attributes:
      label: Choose Your Team
      description: Which team do you want to join? Your choice is locked in for the duration of the game.
      options:
        - '🔴 Red Team (Attacker)'
        - '🔵 Blue Team (Defender)'
    validations:
      required: true
  - type: checkboxes
    id: confirmation-checklist
    attributes:
      label: Confirmation Checklist
      description: Please confirm the following before joining the simulation.
      options:
        - label: I have read and understood the rules, deliverables, and winning conditions in the `level4/README.md`.
          required: true
        - label: I understand that my team has a 48-hour time limit to make a move once our turn begins.
          required: true
        - label: I understand that my team's submission must include a video link as described in the instructions.
          required: true
